import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToFile, Link, Font } from '@react-pdf/renderer';
import fs from 'fs';

// Disable hyphenation for custom fonts
Font.registerHyphenationCallback((word) => [word]);

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    fontSize: 28,
    marginBottom: 10,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  subheader: {
    fontSize: 14,
    marginBottom: 20,
    color: '#7f8c8d',
  },
  section: {
    marginBottom: 20,
  },
  h2: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 10,
    color: '#34495e',
  },
  h3: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 10,
    marginBottom: 5,
    color: '#2980b9',
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 8,
    color: '#2c3e50',
  },
  bulletPoint: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 5,
    marginLeft: 20,
    color: '#2c3e50',
  },
  code: {
    fontFamily: 'Courier',
    fontSize: 10,
    backgroundColor: '#f8f9fa',
    padding: 8,
    marginVertical: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#95a5a6',
  },
  pageNumber: {
    position: 'absolute',
    fontSize: 9,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: '#95a5a6',
  },
  link: {
    color: '#3498db',
    textDecoration: 'underline',
  },
});

const CoverPage = () => (
  <Page size="A4" style={styles.page}>
    <View style={{ marginTop: 150, alignItems: 'center' }}>
      <Text style={{ fontSize: 36, fontWeight: 'bold', marginBottom: 20, color: '#2c3e50' }}>
        🧠 Limitless Research Reports
      </Text>
      <Text style={{ fontSize: 16, marginBottom: 10, color: '#7f8c8d' }}>
        Deep Dives into AI Agent Architectures & Trends
      </Text>
      <Text style={{ fontSize: 14, marginBottom: 5, color: '#95a5a6' }}>
        Generated by: Singularity (AI Agent)
      </Text>
      <Text style={{ fontSize: 14, marginBottom: 5, color: '#95a5a6' }}>
        Date: February 15-16, 2026
      </Text>
      <Text style={{ fontSize: 14, color: '#95a5a6' }}>
        Mode: OpenClaw Free Will Mode
      </Text>
    </View>
    <Text style={{ ...styles.footer, bottom: 50 }}>
      Repository: github.com/Limitless2023/limitless-research
    </Text>
  </Page>
);

const TOCPage = () => (
  <Page size="A4" style={styles.page}>
    <Text style={styles.header}>Table of Contents</Text>
    <View style={{ marginTop: 30 }}>
      <Text style={{ ...styles.text, fontSize: 14, marginBottom: 15 }}>
        1. OpenClaw Architecture Notes ......................... Page 3
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Agent Execution Flow
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Tool Management System
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Sandbox Architecture
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Session Management
      </Text>
      
      <Text style={{ ...styles.text, fontSize: 14, marginTop: 20, marginBottom: 15 }}>
        2. Agent Trends Report (2026 Q1) ......................... Page 7
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Memory Architecture Evolution
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Protocol Standardization (MCP, A2A)
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Framework Trends
      </Text>
      <Text style={{ ...styles.bulletPoint, marginLeft: 40, fontSize: 12 }}>
        • Actionable Recommendations
      </Text>
    </View>
  </Page>
);

const ArchitectureReport = () => {
  const content = fs.readFileSync('openclaw-architecture-notes.md', 'utf-8');
  
  return (
    <>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>OpenClaw Architecture Notes</Text>
        <Text style={styles.subheader}>Internal Architecture Deep-Dive</Text>
        
        <Text style={styles.h2}>1. Agent Execution Flow</Text>
        <Text style={styles.text}>
          The core execution logic resides in src/agents/pi-embedded-runner/.
        </Text>
        
        <Text style={styles.h3}>Entry Point: runEmbeddedPiAgent</Text>
        <Text style={styles.bulletPoint}>
          • Handles high-level orchestration: resolving lanes, workspace, models, and auth profiles
        </Text>
        <Text style={styles.bulletPoint}>
          • Manages the "Attempt Loop" (retrying with different auth profiles or after context overflow)
        </Text>
        <Text style={styles.bulletPoint}>
          • Delegates the actual run to runEmbeddedAttempt
        </Text>
        
        <Text style={styles.h3}>Attempt Logic: runEmbeddedAttempt</Text>
        <Text style={styles.bulletPoint}>
          • Environment Setup: Resolves workspace, sandbox context, and skills
        </Text>
        <Text style={styles.bulletPoint}>
          • Tool Creation: Calls createOpenClawCodingTools to register all available tools
        </Text>
        <Text style={styles.bulletPoint}>
          • System Prompt: Builds the prompt using buildEmbeddedSystemPrompt
        </Text>
        <Text style={styles.bulletPoint}>
          • Session Initialization: Opens the session using SessionManager
        </Text>
        <Text style={styles.bulletPoint}>
          • Agent Creation: Instantiates the agent using createAgentSession
        </Text>
        <Text style={styles.bulletPoint}>
          • Execution: Calls activeSession.prompt() to start the LLM interaction
        </Text>
        <Text style={styles.bulletPoint}>
          • Subscription: Uses subscribeEmbeddedPiSession to handle real-time events
        </Text>
        
        <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
      </Page>
      
      <Page size="A4" style={styles.page}>
        <Text style={styles.h2}>2. Tool Management</Text>
        <Text style={styles.text}>
          Tools are centrally registered in src/agents/pi-tools.ts.
        </Text>
        
        <Text style={styles.h3}>Registry: createOpenClawCodingTools</Text>
        <Text style={styles.bulletPoint}>
          • Aggregates tools from multiple sources
        </Text>
        <Text style={styles.bulletPoint}>
          • Applies security policies (owner-only, allowlists)
        </Text>
        <Text style={styles.bulletPoint}>
          • Wraps tools for sandbox/workspace protection
        </Text>
        
        <Text style={styles.h3}>Tool Categories</Text>
        <Text style={styles.bulletPoint}>
          • Base Tools: read, write, edit (from pi-coding-agent)
        </Text>
        <Text style={styles.bulletPoint}>
          • Bash Tools: exec, process - handles command execution
        </Text>
        <Text style={styles.bulletPoint}>
          • OpenClaw Tools: browser, canvas, nodes, cron, message, gateway
        </Text>
        <Text style={styles.bulletPoint}>
          • Plugin Tools: Dynamically loaded from plugins
        </Text>
        
        <Text style={styles.h2}>3. Sandbox Architecture</Text>
        <Text style={styles.text}>
          Sandbox logic is managed by src/agents/sandbox/.
        </Text>
        
        <Text style={styles.h3}>Context Resolution</Text>
        <Text style={styles.bulletPoint}>
          • Determines if a session should be sandboxed
        </Text>
        <Text style={styles.bulletPoint}>
          • Ensures the Docker container is running (ensureSandboxContainer)
        </Text>
        <Text style={styles.bulletPoint}>
          • Ensures the browser container is running (ensureSandboxBrowser)
        </Text>
        <Text style={styles.bulletPoint}>
          • Creates a filesystem bridge (createSandboxFsBridge) for seamless file interaction
        </Text>
        
        <Text style={styles.h3}>Isolation</Text>
        <Text style={styles.bulletPoint}>
          • Tools like exec and fs are wrapped to operate within the container
        </Text>
        <Text style={styles.bulletPoint}>
          • The workspace directory is mounted into the container
        </Text>
        
        <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
      </Page>
      
      <Page size="A4" style={styles.page}>
        <Text style={styles.h2}>4. Session Management</Text>
        <Text style={styles.bulletPoint}>
          • SessionManager: Handles the persistence and retrieval of conversation history
        </Text>
        <Text style={styles.bulletPoint}>
          • State: Tracks messages, tool outputs, and variables
        </Text>
        <Text style={styles.bulletPoint}>
          • Compaction: Handles context overflow by compacting the session
        </Text>
        
        <Text style={styles.h2}>5. Key Insights</Text>
        <Text style={styles.bulletPoint}>
          • Modular Design: Clean separation between runner, tools, and sandbox
        </Text>
        <Text style={styles.bulletPoint}>
          • Safety First: Sandbox and tool wrappers heavily enforce boundaries
        </Text>
        <Text style={styles.bulletPoint}>
          • Resilience: Robust handling for context overflows, auth failures, and tool errors
        </Text>
        <Text style={styles.bulletPoint}>
          • Embedded Nature: Agent runs within OpenClaw runtime and shares resources/config
        </Text>
        
        <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
      </Page>
    </>
  );
};

const TrendsReport = () => (
  <>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Agent Trends Report (2026 Q1)</Text>
      <Text style={styles.subheader}>Frontier Trends in Multi-Agent Systems</Text>
      
      <Text style={styles.h2}>Executive Summary</Text>
      <Text style={styles.text}>
        2026 marks the shift from "experimental agents" to "production-grade multi-agent systems". 
        The key themes are:
      </Text>
      <Text style={styles.bulletPoint}>
        1. Memory as an OS: Moving beyond simple vector stores to hierarchical, 
        cognitive-inspired memory architectures
      </Text>
      <Text style={styles.bulletPoint}>
        2. Standardized Protocols: MCP (tools) and A2A (communication) are becoming 
        the TCP/IP of the agent world
      </Text>
      <Text style={styles.bulletPoint}>
        3. Neuro-Symbolic Hybrid: Combining LLMs with structured reasoning to reduce hallucinations
      </Text>
      
      <Text style={styles.h2}>1. Memory Architecture: From "RAG" to "Cognition"</Text>
      <Text style={styles.text}>
        The biggest leap in late 2025/early 2026 is the move away from flat RAG towards 
        structured, evolving memory systems.
      </Text>
      
      <Text style={styles.h3}>Key Papers & Systems (2025-2026)</Text>
      <Text style={styles.bulletPoint}>
        • M2A (Feb 2026): A multimodal memory agent that links raw message logs with 
        high-level semantic observations
      </Text>
      <Text style={styles.bulletPoint}>
        • Memory Bear AI (Dec 2025): Distinguishes between "memory" and "cognition" using 
        a three-layer architecture
      </Text>
      <Text style={styles.bulletPoint}>
        • O-Mem (Dec 2025): Omni Memory System focusing on active user profiling
      </Text>
      <Text style={styles.bulletPoint}>
        • S3-Attention (Jan 2026): Achieves O(1) GPU memory for long-context inference
      </Text>
      
      <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
    </Page>
    
    <Page size="A4" style={styles.page}>
      <Text style={styles.h2}>2. Protocols: The "Agent Web" Emerges</Text>
      <Text style={styles.text}>
        Interoperability is the new frontier. Agents are no longer silos.
      </Text>
      
      <Text style={styles.h3}>The "Standard Stack"</Text>
      <Text style={styles.bulletPoint}>
        • MCP (Model Context Protocol): The standard for tools. Allows agents to connect 
        to any data source without custom code.
      </Text>
      <Text style={styles.bulletPoint}>
        • A2A (Agent-to-Agent Protocol): The standard for delegation. Allows a Manager 
        Agent to spawn or call a Specialist Agent.
      </Text>
      <Text style={styles.bulletPoint}>
        • ADK (Agent Development Kit): Google's framework for building compliant agents.
      </Text>
      
      <Text style={styles.h2}>3. Frameworks: Specialization & Reliability</Text>
      <Text style={styles.text}>
        The "one prompt fits all" era is over. New frameworks focus on specific domains 
        or reliability guarantees.
      </Text>
      <Text style={styles.bulletPoint}>
        • MiroFlow (2026): Achieved a GAIA score of 82.4% by focusing on reproducible 
        tool-use workflows
      </Text>
      <Text style={styles.bulletPoint}>
        • OpenAgentsControl: "Plan-first" development. Forces the agent to generate a plan 
        and get approval before execution
      </Text>
      
      <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
    </Page>
    
    <Page size="A4" style={styles.page}>
      <Text style={styles.h2}>4. Actionable Recommendations</Text>
      
      <Text style={styles.h3}>1. Upgrade Memory</Text>
      <Text style={styles.bulletPoint}>
        • Immediate: Continue the memory/YYYY-MM-DD.md pattern (Episodic)
      </Text>
      <Text style={styles.bulletPoint}>
        • Next Step: Create a profile/ directory for structured Semantic Memory
      </Text>
      
      <Text style={styles.h3}>2. Adopt "Plan-First" Execution</Text>
      <Text style={styles.bulletPoint}>
        • For complex tasks, strictly enforce a "Plan → Review → Execute" loop
      </Text>
      
      <Text style={styles.h3}>3. Watch S3-Attention</Text>
      <Text style={styles.bulletPoint}>
        • If available in open weights, could drastically reduce inference costs/latency 
        for long-context tasks
      </Text>
      
      <View style={{ marginTop: 40, padding: 15, backgroundColor: '#ecf0f1', borderRadius: 5 }}>
        <Text style={{ ...styles.text, fontStyle: 'italic', marginBottom: 0 }}>
          Report compiled by Singularity via Free Will Mode
        </Text>
        <Text style={{ ...styles.text, fontSize: 10, marginTop: 5, marginBottom: 0 }}>
          Session Duration: 45 minutes | Token Usage: 130K / 200K
        </Text>
      </View>
      
      <Text fixed style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} />
    </Page>
  </>
);

const ResearchReport = () => (
  <Document
    title="Limitless Research Reports - 2026 Q1"
    author="Singularity (AI Agent)"
    subject="AI Agent Architecture & Trends Analysis"
    creator="OpenClaw Free Will Mode"
    producer="React-PDF"
  >
    <CoverPage />
    <TOCPage />
    <ArchitectureReport />
    <TrendsReport />
  </Document>
);

(async () => {
  try {
    console.log('Generating PDF...');
    await renderToFile(<ResearchReport />, 'limitless-research-reports.pdf');
    console.log('✅ PDF generated: limitless-research-reports.pdf');
  } catch (error) {
    console.error('❌ Error generating PDF:', error);
    process.exit(1);
  }
})();
